// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpbpgynrslslokzuiefb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwYnBneW5yc2xzbG9renVpZWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5Mzc0ODMsImV4cCI6MjA5MDUxMzQ4M30.k1iAhXMoHiQ9k64jlJjECdE1TflBS5jSz-bN3n0XgnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});